--- 
title: "Statistical Analysis in Sociology"
author: "Aaron Gullickson"
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
output: 
  bookdown::pdf_book:
    number_section: false
  bookdown::gitbook:
    split_by: "section+number"
    number_section: false
site: bookdown::bookdown_site
documentclass: book
#bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
#github-repo: rstudio/bookdown-demo
description: "Textbook for Statistical Analysis for University of Oregon Sociology"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 4)
```

```{r echo=FALSE}
load("../example_datasets/movies/movies.RData")
load("../example_datasets/sex/sex.RData")
load("../example_datasets/crimes/crimes.RData")
load("../example_datasets/titanic/titanic.RData")
load("../example_datasets/politics/politics.RData")
load("../example_datasets/students/studentsCurrent.RData")
load("../example_datasets/students/studentsamplingdist.RData")
load("../example_datasets/add_health/addhealth.RData")
load("../example_datasets/nyc_nonprofit/nyc.RData")
preston <- read.csv("../example_datasets/misc/preston.csv")
election <- read.csv("../example_datasets/misc/ecofallacy.csv")
library(pander)
library(ggplot2)
library(scales)
```
 
# Preface {-}

This online textbook combines all of the information taught in my undergraduate statistics course as well as both terms of my introductory graduate statistics course. It is very much a work in progress at the moment. I am adding new chapters and transitioning most of my figures to `ggplot` so you will likely notice many quirks. 
