---
title: "Modeling Categorical Outcomes"
subtitle: "Sociology 513"
author: "Aaron Gullickson"
institute: "University of Oregon"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, uo, uol-fonts, lecture_slides.css]
    self_contained: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: ""
      ratio: 16:10
---

```{r child="setup_chunks.Rmd"}
```

## Jump to...

[Dichotomous Outcomes and the Binomial Distribution](#dichotomous)

[Linear Probability Model](#lpm)

[Generalized Linear Model](#glm)

[Logit Model](#logit-model)

[Models for Polytomous Outcomes](#polytomous-models)

---
```{r child="module7_slides_dichotomous_outcomes.Rmd", eval=TRUE}
```

---
```{r child="module7_slides_lpm.Rmd", eval=TRUE}
```

---
```{r child="module7_slides_glm.Rmd", eval=TRUE}
```

---
```{r child="module7_slides_logit_model.Rmd", eval=TRUE}
```

---
```{r child="module7_slides_polytomous_models.Rmd", eval=TRUE}
```


